version: '3.9'

services:
  web:
    build: .
    container_name: sportswear_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    # depends_on:
    #   - db

  redis:
    image: redis:alpine
    container_name: sportswear_redis
    ports:
      - "6379:6379"

  imgproxy:
    image: darthsim/imgproxy:latest
    container_name: sportswear_imgproxy
    ports:
      - "8080:8080"

volumes:
  static_volume:
  media_volume:
